name: Feature request
description: Propose an improvement or a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What need or current limitation motivates this request?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would the desired API or behavior look like?
      render: python
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
